spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/journey
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show_sql: true
    format_sql: true
    use_sql_comments: true

server:
  compression:
    enabled: true
    min-response-size: 1
  jetty:
    acceptors: 2

log4j:
  rootLogger: DEBUG, R
